### ISSUE TITLE
Conventions pour les URLS (re) sur orderlines, items et lines

### ISSUE THREAD

**Issue by edemagon** [simde-utc/woolly-api#12]
![pb_json](https://user-images.githubusercontent.com/13031480/27194194-f92f4780-5201-11e7-8df6-020175cf50a7.png)

incohérence : l'attributs items ne contient pas d'items mais des orderlines et l'url est allongé + il y a lines dans l'url et non sur orderlines

Donc : 
attribut nommé orderlines + type des objets : orderlines + url http://127.0.0.1:8000/ordelines/id_orderline

**Comment by FCartier** [comment]
Fixed
