### ISSUE TITLE
homogenize URLs to simple URL

### ISSUE THREAD

**Issue by edemagon** [simde-utc/woolly-api#8]
The URL for every data should follow this convention : 
**base_url/data_types** for the array with all the data 
**base_url/data_types/id_data** for a particular record
The type which is declared in the json should be the same in the according URL : 
the type "woollyusertypes" is actually git from the url "utype" or "woolly_user_type" which is not correct. 

examples of corrects URLs  : 
**http://127.0.0.1:8000/items** --> for the specified type "items"
**http://127.0.0.1:8000/itemspecifications** --> for the specified type "itemspecifications"
**http://127.0.0.1:8000/sales** --> for the specified type "sales"
**http://127.0.0.1:8000/woollyusertypes** --> for the specified type "woollyusertypes"

**Comment by FCartier** [comment]
Done.

You can see all the urls at http://127.0.0.1:8000 and /users is working as well but isn't integrated to the root yet.
